name=DXLIB
version=1.6
author=BestTechnology CO.,LTD.
maintainer=tech@bt <spc@besttechnology.co.jp>
sentence=By using this library and DXSHIELD, Dynamixel can be controlled easily.
paragraph=
category=Communication
url=https://www.besttechnology.co.jp/modules/knowledge/?BTE074%20DXSHIELD
architectures=*
